version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://api.cbtmiarridlo.com/api/v1}
        - VITE_REVERB_APP_KEY=${VITE_REVERB_APP_KEY:-pusbcdgudcsfkepuso8p}
        - VITE_REVERB_HOST=${VITE_REVERB_HOST:-api.cbtmiarridlo.com}
        - VITE_REVERB_PORT=${VITE_REVERB_PORT:-6001}
        - VITE_REVERB_SCHEME=${VITE_REVERB_SCHEME:-wss}
    container_name: lunar-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - lunar-network

networks:
  lunar-network:
    driver: bridge